### ISSUE TITLE
Delete duplicated sensor_measurement topic name

### ISSUE THREAD

**Issue by Migran99** [aerostack2-developers/as2_core#2]
The "sensor_measurements tag is already in the topic names in the sensor names.
In sensor.hpp line 74, replace:
`topic_name_ = std::string("sensor_measurements/") + sensor_id_;`

With:
`topic_name_ = sensor_id_;`

**Comment by miferco97** [comment]
solved, now sensor_id_ is removed and only topic_name_ is used.
